version: '3.8'
services:
  koyomi:
    container_name: "koyomi"
    build: .
    restart: always
    volumes:
      - ./logs:/opt/logs/
      - ./koyomibot/config:/opt/koyomibot/config/
    depends_on:
      - "redis"
      - "mongo"
      - "splunk"

  redis:
    container_name: "koyomi-redis"
    image: "redis:alpine"
    restart: always

  mongo:
    container_name: "koyomi-mongo"
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /opt/koyomibot/db:/data/db
